version: '3'
services:
  lb-a:
    image: wilfongjt/lb-a
    build:
      context: ./lb-a
    command: >
      bash -c "npm install && npm install nodemon && npm run dev"
    volumes:
      - ./lb-a:/usr/src
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=${NODE_ENV}
      - LB_ENV=development
      - LB_A_PORT=${LB_A_PORT}
      - LB_HAPI=${HAPI_URL}
      - HAPI_URL=http://${HAPI_HOST}:${HAPI_PORT}
    links:
      - hapi:hapi

  #lb-b:
  #  image: wilfongjt/lb-b
  #  build:
  #    context: ./lb-b
  #  command: >
  #    bash -c "npm install && npm install nodemon && npm run dev"
  #  volumes:
  #    - ./lb-b:/usr/src
  #  ports:
  #    - 3001:3001
  #  environment:
  #    - NODE_ENV=${NODE_ENV}
  #    - LB_ENV=development
  #    - LB_B_PORT=${LB_B_PORT}

  hapi:
    image: wilfongjt/hapi-api
    build:
      context: ./hapi-api
    command: >
      sh -c "npm install && npm install nodemon && npm run dev"
    volumes:
      - ./hapi-api:/usr/src/api
    ports:
      - 5555:5555
    environment:
      - NODE_ENV=${NODE_ENV}
      - HAPI_PORT=${HAPI_PORT}
      - HAPI_HOST=${HAPI_HOST}
