version: '3'
services:
  lb-a:
    image: wilfongjt/lb-a
    build:
      context: ./lb-a
    command: >
      bash -c "npm install && npm run dev" 
    volumes:
      - ./:/usr/src
    ports:
      - 3000:3000
    environment:
      - LB_ENV=
  lb-b:
    image: wilfongjt/lb-b
    build:
      context: ./lb-b
    command: >
      bash -c "npm install && npm run dev" 
    volumes:
      - ./:/usr/src
    ports:
      - 3000:3001
    environment:
      - LB_ENV=
